---
title: "Dryland grain yield"
output: github_document
---
# Load packages
```{r,message=FALSE}
library(readxl)
library(tidyverse)
library(pbkrtest)
library(agricolae)
library(emmeans)
library(multcomp)
library(multcompView)
library(lme4)
library(lmerTest)
```
# load data
```{r}
dry.grainyield <- read_excel("grain yield2.xlsx")

```


# Convert character to factors
```{r}
dry.grainyield$crop<-as.factor(dry.grainyield$crop)
dry.grainyield$nitrogen<-as.factor(dry.grainyield$nitrogen)
dry.grainyield$year<-as.factor(dry.grainyield$year)
dry.grainyield$location<-as.factor(dry.grainyield$location)

```
# Summary and attaching data
```{r}
summary(dry.grainyield)
attach(dry.grainyield)

```
# subset the file by crop
```{r}
einkorn <- subset(dry.grainyield, crop=='Einkorn')
emmer <- subset(dry.grainyield, crop=='Emmer')
spelt <- subset(dry.grainyield, crop=='Spelt')

```

# subset the file by location
```{r}
SAREC <- subset(dry.grainyield, location=='SAREC')
ShREC <- subset(dry.grainyield, location=='ShREC')

```
# Anova by crop
```{r}
fit <- lmer(`yield (kg/ha)` ~ location*nitrogen + (1 | year), data = einkorn)
anova(fit)
ranova(fit)
fit3 <- lmer(`yield (kg/ha)` ~ location*nitrogen + (1 | year), data = emmer)
anova(fit3)
ranova(fit3)
fit5 <- lmer(`yield (kg/ha)` ~ location*nitrogen + (1 | year), data = spelt)
anova(fit5)
ranova(fit5)

```
# Anova by location
```{r}
fit9 <- lm(`yield (kg/ha)` ~ crop, data = SAREC)
anova(fit9)
crop.cld<-cld(emmeans(fit9, ~crop), Letters=LETTERS, reverse=TRUE) 
crop.cld
fit10 <- lmer(`yield (kg/ha)` ~ crop + (1 | year), data = ShREC)
anova(fit10)
ranova(fit10)
crop.cld1<-cld(emmeans(fit10, ~crop), Letters=LETTERS, reverse=TRUE) 
crop.cld1
```

# Visualize the data
```{r}
dry.grainyield %>% 
  ggplot(mapping=aes(y=`yield (kg/ha)`,x=nitrogen,color=crop))+
  geom_boxplot()

dry.grainyield %>% 
  ggplot(mapping=aes(y=`yield (kg/ha)`,x=location,color=crop))+
  geom_boxplot()

dry.grainyield %>% 
  ggplot(mapping=aes(y=`yield (kg/ha)`,x=location))+
  geom_col(aes(fill=crop))


```







